version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: just-golf-pg-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  just-golf-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: just-golf-go-app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_CONN}
    ports:
      - "${APP_PORT}"

volumes:
  postgres_data:

